### ISSUE TITLE
Create a website for homeferences

### ISSUE THREAD

**Issue by luisFilipePT** [homeferences/list#7]
Hi, can I start a website for this, any interest on that?

Plan:
*  Create a branch master and open a PR for a Gatsby application where conferences could be added by markdown pages upon PR's
* Deploy it to netlify

Can I pick this up?

**Comment by coderbyheart** [comment]
Sure, I am not working on a more fancy view of the data. 
IMO we should keep the information here limited to _discovery_ of events, not replacing the individual event websites. Having too much duplicate information will lead to more work and more confusion. 

That said, a simple website that builds on the static markdown table as the source can have useful features like:
- filtering (by past / future events, free / paid events, topic)
- better mobile experience

**Comment by luisFilipePT** [comment]
I agree with you, I will put up some simple MVP however I guess I have a blocker:

* It would be better for `homeferences` to have a `Netlify` acount to make it live, under my account is cumbersome.
* Since I would also need to allow netlify on github I would probably need to be an admin or you to approve

What do you think? If you believe it's too much trouble I can do it under my github and just link to this repo

**Comment by coderbyheart** [comment]
Sure,
I have created https://homeferences.netlify.com/ and added you as maintainer to the [website](https://github.com/homeferences/website) repository.

**Comment by luisFilipePT** [comment]
@coderbyheart So I created the branch `master` for the website repo and added a the events from April.

If possible can you update the setting in `netlify` to this ones?

![image](https://user-images.githubusercontent.com/9373787/76790612-18255f80-67b7-11ea-8153-77207770c935.png)

Then we should protect `master` to not accept push's and everything from now on should come as a PR and one approval from maintainers needed.

The site is like this now:

![localhost_8000_](https://user-images.githubusercontent.com/9373787/76790737-53c02980-67b7-11ea-817e-0abacb3b2c5d.png)

After this being done I write documentation on how to `Add conferences` and create a list of issues for people to pickup, I think I can get some help in the next days if this gains traction, you can also reach out on twitter and announce the site and we can see if anyone steps up.

Let me know what you think.

My next steps are:
* How can people contribute with new events
* Improve About Page
* Write issues for people to pickup (ex: search by tags, improve navigation, etc)

**Comment by coderbyheart** [comment]
1. I changed the main branch to `main` and updated it on Gatsby
2. I really like the clean design, works nice on mobile too.
3. the source for the site should be the [README.md](https://github.com/homeferences/list/blob/saga/README.md), it's very easy to quickly consume (no pagination), to share AND easy to contribute to (plaintext over JSON).
   1. Pictures can be taken from `og:graph` images in the sites meta data
   2. No need for having individual pages for each event (as I said, I don't want to duplicate too much info), directly link to the event site
    3. Given that a filter feature would be the one advantage over the static list, I think a dynamic list with endless scrolling and toggle-able filters could work nicely (using e.g. a static JSON built from the markdown table)

**Comment by luisFilipePT** [comment]
I will update this probably tomorrow:

> 1. I changed the main branch to `main` and updated it on Gatsby
ok
> 2. I really like the clean design, works nice on mobile too.  

Nice

> 3. the source for the site should be the [README.md](https://github.com/homeferences/list/blob/saga/README.md), it's very easy to quickly consume (no pagination), to share AND easy to contribute to (plaintext over JSON).
     
Ok, probably will copy the readme to the website repo.

   
>    1. Pictures can be taken from `og:graph` images in the sites meta data

Maybe replace with something related to `homeferences`? So that people can share nicely formatted.
    
>    2. No need for having individual pages for each event (as I said, I don't want to duplicate too much info), directly link to the event site
   
   Will remove the detail and just add the link to the cards
   
>    3. Given that a filter feature would be the one advantage over the static list, I think a dynamic list with endless scrolling and toggle-able filters could work nicely (using e.g. a static JSON built from the markdown table)

    
ok, will remove pagination and test infinite scroll

**Comment by coderbyheart** [comment]
I am publishing a JSON now on every change to https://homeferences.github.io/list/homeferences.json

**Comment by luisFilipePT** [comment]
> I am publishing a JSON now on every change to https://homeferences.github.io/list/homeferences.json

That's great I was testing with a `yaml` file, but I can use that 😄 
Let me just suggest a field with an array of tags `tags: ["js", "css"]`.
For now I will copy the file to the other repo and later maybe we could just merge the repos?

**Comment by razbakov** [comment]
The list on website is not yet dynamic, is it?

**Comment by coderbyheart** [comment]
> > I am publishing a JSON now on every change to https://homeferences.github.io/list/homeferences.json
> 
> That's great I was testing with a `yaml` file, but I can use that 
> Let me just suggest a field with an array of tags `tags: ["js", "css"]`.

Well, someone™ first needs to add tags to the list of homeferences, than I can look into adding it to the JSON.

> For now I will copy the file to the other repo and later maybe we could just merge the repos?

If you are making it dynamic, you could just load it in the browser from the URL, no need to copy it around.

**Comment by coderbyheart** [comment]
> The list on website is not yet dynamic, is it?

No.

**Comment by luisFilipePT** [comment]
> > The list on website is not yet dynamic, is it?
> 
> No.

In the open PR it is ;)

**Comment by coderbyheart** [comment]
Thank you all for this amazing effort!
We'll continue the collaboration over here: https://github.com/homeferences/website
